name: Java Program Build & Workflow Success/Failure Notification

on: push

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'

      # - name: Debug file structure (for troubleshooting)
      #   run: |
      #     echo "Printing the file structure..."
      #     pwd  # Print working directory
      #     ls -la  # List files to confirm HelloWorld.java exists

      # - name: Compile Java program
      #   run: |
      #     echo "Compiling the Java program..."
      #     javac HelloWorld.java

      # - name: Run Java program
      #   run: |
      #     echo "Running the Java program..."
      #     java HelloWorld

      - name: java
        run: echo "Hello Rohan..."

  notify:
    runs-on: ubuntu-latest
    needs: java-build  # This makes sure `notify` runs after `java-build`

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email notification
        run: |
          # Check the status of the previous step (java-build) and set the status accordingly
          if [[ ${{ needs.java-build.result }} == 'success' ]]; then
            STATUS="success"
          else
            STATUS="failure"
          fi

          # Define the subject and message
          SUBJECT="GitHub Workflow $STATUS"
          MESSAGE="The workflow has $STATUS. Please check the logs."
          
          if [[ "$STATUS" == "success" ]]; then
            MESSAGE="The Java program built and ran successfully, and the workflow completed successfully!"
          fi

          # Send email using SMTP (Gmail)
          curl --url "smtp://smtp.gmail.com:587" \
            --ssl-reqd \
            --mail-from "${{ secrets.SMTP_USERNAME }}" \
            --mail-rcpt "${{ secrets.SMTP_TO_EMAIL }}" \
            --upload-file <(echo -e "From: ${SMTP_USERNAME}\nTo: ${SMTP_TO_EMAIL}\nSubject: $SUBJECT\n\n$MESSAGE") \
            --user "${{ secrets.SMTP_USERNAME }}:${{ secrets.SMTP_PASSWORD }}"
