name: Java Program Build & Workflow Success/Failure Notification

on: push

jobs:
  java-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Optionally, set up JDK, compile and run the Java program here if necessary
      # - name: Set up JDK 11
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '11'

      # - name: Compile Java program
      #   run: |
      #     echo "Compiling the Java program..."
      #     javac HelloWorld.java

      # - name: Run Java program
      #   run: |
      #     echo "Running the Java program..."
      #     java HelloWorld

      - name: Dummy Java Task
        run: echo "Hello from the Java Build step!"

  notify:
    runs-on: ubuntu-latest
    needs: java-build  # This ensures `notify` runs after `java-build`

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Email notification
        run: |
          # Set status to success directly
          STATUS="success"

          # Define the subject and body of the email based on the status
          SUBJECT="GitHub Workflow Status: $STATUS"
          MESSAGE="The workflow has completed with a $STATUS status. Please check the logs for details."
          
          if [[ "$STATUS" == "success" ]]; then
            MESSAGE="The Java program built and ran successfully, and the workflow completed successfully!"
          fi

          # Send email using SMTP (Gmail)
          curl --url "smtp://smtp.gmail.com:587" \
            --ssl-reqd \
            --mail-from "${{ secrets.SMTP_USERNAME }}" \ 
            --mail-rcpt "${{ secrets.SMTP_TO_EMAIL }}" \
            --upload-file <(echo -e "From: ${{ secrets.SMTP_USERNAME }}\nTo: ${{ secrets.SMTP_TO_EMAIL }}\nSubject: $SUBJECT\n\n$MESSAGE") \
            --user "${{ secrets.SMTP_USERNAME }}:${{ secrets.SMTP_PASSWORD }}"
